# Generated by Django 5.1 on 2024-08-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_name", models.CharField(max_length=200)),
                ("serial_number", models.CharField(max_length=50, unique=True)),
                ("price", models.PositiveIntegerField()),
                ("color", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=1000)),
                ("certification", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["asset_name"],
            },
        ),
    ]
